import React from 'react';
    import { motion } from 'framer-motion';
    import { FaBriefcase, FaBuilding, FaCalendar } from 'react-icons/fa';

    function Experience() {
      return (
        <motion.section
          id="experience"
          initial={{ opacity: 0, y: 50 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <h2>Professional Experience</h2>
          <motion.div
            className="experience-item"
            whileHover={{ scale: 1.02 }}
          >
            <h3>
              <FaBuilding /> AnandaAI – Hartford, CT (USA)
            </h3>
            <h4>
              <FaBriefcase /> Work-stream Leader, GenAI engineer
              <span style={{ marginLeft: '5px' }}>
                <FaCalendar /> (Aug 2024 – Dec 2024)
              </span>
            </h4>
            <ul>
              <li>Leading a cross-functional team as the Work-stream Leader for a capstone project, driving collaboration across development, data analysis, and engineering streams to meet project milestones.</li>
              <li>Actively designing and fine-tuning Large Language Models (LLMs) as a GenAI Engineer, leveraging domain-specific Q&A datasets to enhance chatbot accuracy and reliability.</li>
              <li>Conducted exploratory data analysis (EDA) and integrating insights to train AI models, focusing on improving domain-specific conversational capabilities for a cryptocurrency-focused chatbot.</li>
              <li>Participating in code reviews and developing an evaluation framework to measure the quality and relevance of answers generated by the LLM.</li>
            </ul>
          </motion.div>
          <motion.div
            className="experience-item"
            whileHover={{ scale: 1.02 }}
          >
            <h3>
              <FaBuilding /> Yodaplus – Pune (India)
            </h3>
            <h4>
              <FaBriefcase /> Senior Software Developer
              <span style={{ marginLeft: '5px' }}>
                <FaCalendar /> (July 2022-July 2023)
              </span>
            </h4>
            <ul>
              <li>Engaged with IDB Invest, providing solutions to complex cross-system problems by integrating MSSQL data requests, Java APIs, and Azure Service Bus, reducing 80% of recurring errors and enhancing audit efficiency.</li>
              <li>Developed APIs and features for the Credit Risk Management Tool (FACT) in collaboration with Moody’s Analytics using the .NET framework (C#), reducing vendor costs by 50% through proprietary system enhancements.</li>
              <li>Created pipelines using Azure Function Apps to seamlessly integrate company data hubs with external data sources such as S&P and Bloomberg, ensuring smooth information exchange.</li>
              <li>Acted as the primary point of contact for IDB Invest, collaborating across technical and business teams to resolve issues and ensure smooth project execution while displaying strong communication skills.</li>
              <li>Mentored team members on coding best practices and project management strategies, resulting in a 1.5x increase in sprint efficiency.</li>
            </ul>
          </motion.div>
          <motion.div
            className="experience-item"
            whileHover={{ scale: 1.02 }}
          >
            <h3>
              <FaBuilding /> Larsen & Toubro Technologies and Services – Mysore (India)
            </h3>
            <h4>
              <FaBriefcase /> Associate Software Developer
              <span style={{ marginLeft: '5px' }}>
                <FaCalendar /> (June 2021 - June 2022)
              </span>
            </h4>
            <ul>
              <li>Developed solutions from scratch for Skywise (Airbus) on their online tool first by performing some exploratory data analysis (EDA) and then using PySpark, SQL, HTML and JavaScript as per demand from various airline companies like SAS airlines.</li>
            </ul>
          </motion.div>
          <motion.div
            className="experience-item"
            whileHover={{ scale: 1.02 }}
          >
            <h3>
              <FaBuilding /> Global Engineering Academy (LTTS) – Mysore (India)
            </h3>
            <h4>
              <FaBriefcase /> Intern
              <span style={{ marginLeft: '5px' }}>
                <FaCalendar /> (Feb 2021 - May 2021)
              </span>
            </h4>
            <ul>
              <li>Worked towards becoming a C# full stack developer. Got hands-on on many projects in different .NET frameworks based on requirements.</li>
              <li>Got into a team of elite people among the batchmates to work on special projects with our mentor.</li>
            </ul>
          </motion.div>
           <motion.div
            className="experience-item"
            whileHover={{ scale: 1.02 }}
          >
            <h3>
              <FaBuilding /> VSS Tech Solutions, Bangalore
            </h3>
            <h4>
              <FaBriefcase /> Android Developer
              <span style={{ marginLeft: '5px' }}>
                <FaCalendar /> (Oct 2020- Jan 2021)
              </span>
            </h4>
            <ul>
              <li>Worked as an android developer focusing on UI add-ons and implementing various APIs for their blue-collar hiring application in the market.</li>
            </ul>
          </motion.div>
        </motion.section>
      );
    }

    export default Experience;
